@startuml
title __classes__


' classes

json tasks_list {
    "task" : [
        "properties",
        "...",
        "properties"
    ]
}

class Core {
    current_mode
    add_input()
    rm_input()
    update()
    display()
}

class ChooseMood {
    mood_1 : button
    mood_2 : button
    mood_3 : button
    none : button
    update()
    display()
}

class TaskList {
    matching_tasks : list of Tasks
    selected_task : bool
    grid
    editor
    filter : dict
    update()
    display()
}

json filter {
    "fini" : "bool",
    "max_difficulty" : "int",
    "min_difficulty" : "int",
    "max_long" : "int",
    "min_long" : "int"
}

class Task {
    properties : dict
    hit_box
    update()
    display()
}

json properties {
    "name" : "str",
    "description" : "str",
    "fini" : "bool",
    "difficulté" : "int",
    "longueur" : "int"
}

class TaskEditor {
    task : Task
    name : ligne de texte
    description : text area
    fini : checkbox
    difficulté : curseur
    longueur : curseur
    enregistrer : button
    supprimer : button
    update()
    display()
}


' relations

Core::current_mode -left-> ChooseMood
Core::current_mode -down-> TaskList

Task::properties -right-> properties

TaskList::filter --> filter
TaskList::editor -down-> TaskEditor
TaskList::matching_tasks -right-> Task

TaskEditor::task -up-> properties

@enduml